<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >

<?php 

echo $this->headScript()->
	   appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
       appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
       appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
       appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
       appendFile($this->baseUrl() . "/js/bootstrap.js")->
       appendFile($this->baseUrl() . "/js/jsmodulos/planes.js")->
       appendFile($this->baseUrl() . "/js/grillasmodulos/gridPlanes.js")->
       appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
       appendFile($this->baseUrl() . "/js/jquery.blockUI.js");




echo $this->headLink()
	        ->setIndent('  ')
	        ->prependStylesheet($this->baseUrl() . "/css/ui.datepicker.css")
	        ->prependStylesheet($this->baseUrl() . "/css/bootstrap.css")
			->prependStylesheet($this->baseUrl() . "/css/jquery-ui-1.8.17.custom.css")
	        ->prependStylesheet($this->baseUrl() . "/css/bootstrap.css")
	        ->prependStylesheet($this->baseUrl() . "/css/ui.jqgrid.css")
	        ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/planes.css")
			->prependStylesheet($this->baseUrl() . "/css/contenedor.css");
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<body>
	  
	<CENTER>
	
	<!-- base semi-transparente -->
	<div id="fade" class="overlay" onclick = "document.getElementById('light').style.display='none';document.getElementById('fade').style.display='none'"></div> 
	<!-- fin base semi-transparente -->

<!--	<div id="light" class="moda" style="height:450px;left:5%;top:5%;">
		<center>
						<div id="cabeceraFormulario" class="btn btn-info">
			   				<h1 id="cabecera-form" align="center" style="margin-bottom: 20px;color:white;">Producto</h1>
					    	<div class="alert alert-block hide" id="warning-block-producto">
					    		<div id="warning-message-producto"></div>
	      					</div>
	      					<div class="alert alert-success hide" id="success-block">
				        		Los datos han sido almacenados exitosamente
			      			</div>
			      			<div class="alert alert-error hide" id="error-block">
				    		</div>
			      			<div class="alert alert-success hide" id="limpiar-block"></div>
			      		</div>
				
			      		    <div id="contenedor">
				    		<fieldset>
								  <table border="0">
								    <tr>
								    	<td style="align:left;"><label for="descripcionproducto" id="descripcionproducto-idioma">Descripci&oacuten del Producto</label></td>
								    	<td><input id="descripcionproducto" style="width:300px;" ></input></td>
									</tr>
								</table>
							</fieldset>
							
					</div>
					<div id="contenedor">
		 		   		<a id="buscarproductomodal"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Buscar"  style="cursor: hand;"/></a>
		 		   </div> 
					
				<div id="contenedor" style="height:200px;">
					<fieldset>
						<table border="0">
							<tr>
								<td>
									<div class="tab-content" id="tab-content">
										<div id="grillaPaginadorProductos">
											<table id="grillaProductos"></table>
											<div id="paginadorProductos"></div>
										</div>
									</div>
								</td>
							</tr>
						</table>
					</fieldset>
				</div>
		<div class="modal-footer">
		  	    		<fieldset>
								  <table border="0">
								  	<tr>
										<td>
										<button class="btn btn-info" id="bot-guardar-select">Seleccionar</button>
										<button class="btn" id="cancelar">Cancelar</button>
										</td>
									</tr>
								</table>
							</fieldset>
					</div>
		</center>
	</div> -->
	
	<div id="light-modal" class="moda" style="height:575px;display:none;border:0px;padding:5px 0;border: 2px solid #C6E9FF;border-color: #BCE8F1;background: #49AFCD;">
	               <input id="id-producto-modal" type="hidden">
	               <h1 id="cabecera-form" align="center" style="margin-bottom: 20px;color:white;height:15px;"><div id="editar-nuevo">Nuevo Plan</div></h1>
					     <div class="alert alert-block hide" id="warning-block">
				    		<div id="warning-message"></div>
      					</div>
      					<div class="alert alert-success hide" id="success-block">
			        		Los datos han sido almacenados exitosamente
		      			</div>
		      			<div class="alert alert-error hide" id="error-block">
			    		</div>
		      			<div class="alert alert-success hide" id="limpiar-block"></div>

		             <div id="contenedor-modal" style="padding:5px 0;border: 2px solid #C6E9FF;border-color: #BCE8F1;background: #D9EDF7;">
		            	<table>
		            		<tr>
		            			<td><label for="codigoplan-modal" id="codigoplan-modal-idioma">C&oacutedigo del Plan<font style="color: red;">(*)</font></label></td>
								<td><input id="codigoplan-modal" maxlength="4" style="width:50px;" onkeypress="return validarNumerosLetrasPorcentageEspacio(event);"></input></td>
								<td><label for="empresaplan-modal" id="empresaplan-modal-idioma">Empresa <font style="color: red;">(*)</font></label></td>
								<td><select class="input-small" name="empresaplan-modal" id="empresaplan-modal" style="width:150px;" onchange="cargarSucursal(this,null,false);"><option value="-1">---Seleccione---</option></select></td>
									    
							</tr>
							<tr>
		            			<td><label for="nombreplan-modal" id="nombreplan-modal-idioma">Nombre del Plan<font style="color: red;">(*)</font></label></td>
								<td><input id="nombreplan-modal" maxlength="30" style="width:150px;" onkeypress="return validarNumerosLetrasPorcentageEspacio(event);"></input></td>
								<td><label for="sucursal-modal" id="sucursal-modal-idioma">Sucursal <font style="color: red;">(*)</font></label></td>
								<td><select class="input-small" name="sucursal-modal" id="sucursal-modal" style="width:150px;"><option value="-1">---Seleccione---</option></select></td>
									    
							</tr>
							<tr>
		            			<td><label for="monedaplan-modal" id="monedaplan-modal-idioma">Moneda del Plan <font style="color: red;">(*)</font></label></td>
								<td><select class="input-small" name="monedaplan-modal" id="monedaplan-modal" style="width:150px;"><option value="-1">---Seleccione---</option></select></td>
								<td><label for="unidadtarifa-modal" id="unidadtarifa-modal-idioma">Unidad de Medida <font style="color: red;">(*)</font></label></td>
								<td><select class="input-small" name="unidadtarifa-modal" id="unidadtarifa-modal" style="width:150px;"><option value="-1">---Seleccione---</option></select></td>
							</tr>
							<tr>
								<td><label for="cantidadperiodos" id="cantidadperiodos-idioma">Cantidad de periodos a facturar <font style="color: red;">(*)</font></label></td>
								<td><input id="cantidadperiodos" maxlength="2" style="width:150px" onkeydown='return ( event.ctrlKey || event.altKey || (47 < event.keyCode && event.keyCode<58 && event.shiftKey==false) || (95 < event.keyCode && event.keyCode<106) || (event.keyCode==8) || (event.keyCode==9) || (event.keyCode==110) || (event.keyCode==190) || (event.keyCode>34 && event.keyCode<40) || (event.keyCode==46) )'/></td>
								<td><label for="periodofacturacion-modal" id="periodofacturacion-modal-idioma">Periodo de facturaci&oacuten <font style="color: red;">(*)</font></label></td>
								<td><select class="input-small" name="periodofacturacion-modal" id="periodofacturacion-modal" style="width:150px;"><option value="-1">---Seleccione---</option></select></td>
							</tr>
							<tr>
								<td><label for="porcentajemora" id="porcentajemora-idioma">Porcentaje de la mora </label></td>
								<td><input id="porcentajemora"  style="width:150px" onkeydown='return ( event.ctrlKey || event.altKey || (47 < event.keyCode && event.keyCode<58 && event.shiftKey==false) || (95 < event.keyCode && event.keyCode<106) || (event.keyCode==8) || (event.keyCode==9) || (event.keyCode==110) || (event.keyCode==190) || (event.keyCode>34 && event.keyCode<40) || (event.keyCode==46) )'/></td>
							    <td><label for="producto" id="producto-idioma">Producto <font style="color: red;">(*)</font> </label></td>
								<td><input id="producto-modal" readonly="readonly" maxlength="50" style="width:150px;" ></input>
									<a id="producto-modal-select"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/lupa-select.png"; ?>" id="buscar-select-img" title="Buscar"  style="cursor: hand;"/></a></td>
		 		   			</tr>
		 		   			<tr>
								<td><label for="costoplan" id="costoplan-idioma">Costo del Plan </label></td>
								<td><input id="costoplan" maxlength="15" style="width:150px" onkeydown='return ( event.ctrlKey || event.altKey || (47 < event.keyCode && event.keyCode<58 && event.shiftKey==false) || (95 < event.keyCode && event.keyCode<106) || (event.keyCode==8) || (event.keyCode==9) || (event.keyCode==110) || (event.keyCode==190) || (event.keyCode>34 && event.keyCode<40) || (event.keyCode==46) )'/></td>
								<td><label for="periodoespera-modal" id="periodoespera-modal-idioma">Periodo de Espera </label></td>
								<td><select class="input-small" name="periodoespera-modal" id="periodoespera-modal" style="width:150px;"><option value="-1">---Seleccione---</option></select></td>
							</tr>
							<tr>
								<td><label for="cantidadlimitemensual" id="cantidadlimitemensual-idioma">Cantidad L&iacutemite Mensual </label></td>
								<td><input id="cantidadlimitemensual" maxlength="9" style="width:150px" /></td>
								<td><label for="tiempoespera" id="tiempoespera-idioma">Tiempo de Espera a aplicar </label></td>
								<td><input id="tiempoespera" maxlength="9" style="width:150px" onkeydown='return ( event.ctrlKey || event.altKey || (47 < event.keyCode && event.keyCode<58 && event.shiftKey==false) || (95 < event.keyCode && event.keyCode<106) || (event.keyCode==8) || (event.keyCode==9) || (event.keyCode==110) || (event.keyCode==190) || (event.keyCode>34 && event.keyCode<40) || (event.keyCode==46) )'/></td>
							</tr>
							</table>
							<table>
							<tr>
								<td>
									<fieldset style="font: bold;background:#49AFCD;color:white;padding:5px;">
										<table>
											<tr>
												<td><label for="montoinicialnocobrado" id="montoinicialnocobrado-idioma" style="padding:5px;color:white;">Monto inicial no cobrado </label></td>
												<td><input id="montoinicialnocobrado" maxlength="15" style="width:150px" onkeydown='return ( event.ctrlKey || event.altKey || (47 < event.keyCode && event.keyCode<58 && event.shiftKey==false) || (95 < event.keyCode && event.keyCode<106) || (event.keyCode==8) || (event.keyCode==9) || (event.keyCode==110) || (event.keyCode==190) || (event.keyCode>34 && event.keyCode<40) || (event.keyCode==46) )'/></td>
											</tr>
											<tr>
												<td><label for="cantidadunidadtarifasnocobradas" id="cantidadunidadtarifasnocobradas-idioma" style="padding:5px;color:white;">Cantidad de U. de Tarifas no Cobradas </label></td>
												<td><input id="cantidadunidadtarifasnocobradas" maxlength="9" style="width:150px" /></td>
											</tr>
											<tr>
												<td><label for="arbollabel_modal" id="descripcionproductoportugues-idioma" style="font: bold;color:white;padding:5px;">Permitir pasar el l&iacutemite del periodo de facturaci&oacuten (S/N)</label></td>
												<td><fieldset style="font: bold;background:#49AFCD;color:white"><input type="radio" name="group1" id="permitirpasar-si">S&iacute<br>
												<input type="radio" name="group1" checked value="SEPARADO" id="permitirpasar-no">No</fieldset></td>
											</tr>
										</table>
										</fieldset>
								</td>
								<td>
									<fieldset style="font: bold;background:#49AFCD;color:white;padding:1px;">
										<table>
											<tr>
												<td><label for="arbollabel_modal" id="descripcionproductoportugues-idioma" style="font: bold;color:white;padding:5px;">Aplicar Multa</label></td>
												<td><fieldset style="font: bold;background:#49AFCD;color:white"><input type="radio"  name="group2" id="aplicarmulta-si" onclick="habilitarOpciones();">S&iacute
												<input type="radio" name="group2"  checked value="SEPARADO" id="aplicarmulta-no" onclick="esconderOpciones();">No</fieldset></td>
											</tr>
											<tr id ="opciones-multa" style="display:none;">
												<td><label for="periodomulta-modal" id="periodomulta-modal-idioma" style="padding:5px;color:white;">Periodo de la Multa <font style="color: red;">(*)</font></label></td>
												<td><select class="input-small" name="periodomulta-modal" id="periodomulta-modal" style="width:150px;"><option value="-1">---Seleccione---</option></select></td>
												<td><label for="redondeomulta-modal" id="redondeomulta-modal-idioma" style="padding:5px;color:white;">Redondeo de la Multa <font style="color: red;">(*)</font></label></td>
												<td><select class="input-small" name="redondeomulta-modal" id="redondeomulta-modal" style="width:150px;"><option value="-1">---Seleccione---</option>
																																				 <option value="0">Ajuste Inferior</option>
																																				 <option value="1">Ajuste Superior</option></select></td>
											</tr>
											<tr id ="opciones-multa2" style="display:none;">
												<td><label for="multa" id="multa-idioma" style="padding:5px;color:white;">Multa <font style="color: red;">(*)</font></label></td>
												<td><input id="multa" style="width:150px" onkeydown='return ( event.ctrlKey || event.altKey || (47 < event.keyCode && event.keyCode<58 && event.shiftKey==false) || (95 < event.keyCode && event.keyCode<106) || (event.keyCode==8) || (event.keyCode==9) || (event.keyCode==110) || (event.keyCode==190) || (event.keyCode>34 && event.keyCode<40) || (event.keyCode==46) )'/></td>
												<td><label for="formapago-modal" id="formapago-modal-idioma" style="padding:5px;color:white;">Forma de Aplicaci&oacuten de la Multa <font style="color: red;">(*)</font></label></td>
												<td><select class="input-small" name="formapago-modal" id="formapago-modal" style="width:150px;"><option value="-1">---Seleccione---</option>
																																				 <option value="0">Porcentual</option>
																																				 <option value="1">Monto Fijo</option></select></td>
											</tr>
										</table>
										</fieldset>
								</td>
								<td style="padding:5px;"></td>
							
							</tr>
							</table>
							</div>
						<div id="contenedor-modal" style="text-align:left;padding:5px 0;border: 2px solid #C6E9FF;border-color: #BCE8F1;background: #D9EDF7;">
		            		<strong style="text-align:left;"><font style="color: red;">(*)</font> Complete los campos marcados en el formulario para guardar el Plan</strong>
      					</div>
      					<div class="modal-footer">
				              <a data-dismiss="modal" class="btn" href="#" id="cancelarplan-modal">Cancelar</a>
				              <a class="btn btn-info" id="guardar-plan" href="#">Guardar</a>
		            	</div>
          		</div>
		            
	<div id="listado-gestionplan" style="display:none;">  
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span10">
			<br>
					<div id="cabeceraFormulario" class="btn btn-info" style="width:1100px;">
		   				<h1 id="cabecera-titulo" align="center" style="margin-bottom: 20px;color:white;">Planes Disponibles por Empresa</h1>
				    			      		
				    <div class="alert alert-block hide" id="warning-block-title">
				    		<div id="warning-message-title"></div>
      				</div>
      				
      				<div class="alert alert-success hide" id="success-block-title">
			        		<div id="success-message-title"></div>
		      		</div>
		      		
		      		<div class="alert alert-info hide" id="info-block-listado">
						    		<div id="info-message"></div>
		      		</div>
      				
				    </div>
				<input type="hidden" id="id-producto"></input>
				<input type="hidden" id="id-plan"></input>
				
				<div  id="clientes-div">
		 		    <div id="contenedor" style="width:1100px;">
				    			<fieldset>
								  <table border="0">
								    <tr>
								    	<td><label for="codigoplan" id="codigoplan-idioma">C&oacutedigo de Plan</label></td>
								    	<td><input id="codigoplan" maxlength="4" style="width:50px;" onkeypress="return validarNumerosLetrasPorcentageEspacio(event);"></input></td>
									  	<td><label for="empresa" id="empresa-idioma">Empresa</label></td>
									    <td><select class="input-small" name="empresa" id="empresa" style="width:150px;" onchange="cargarSucursalList(this,null,false);"><option value="-1">---Seleccione---</option></select></td>
									    <td><label for="producto" id="producto-idioma">B&uacutesqueda de Producto</label></td>
									    <td><input id="producto" readonly="readonly" maxlength="150" style="width:150px;" ></input>
									  		<a id="buscarproducto-select"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/lupa-select.png"; ?>" id="buscar-select-img" title="Buscar"  style="cursor: hand;"/></a></td>
		 		   				    </tr>
									<tr>
								    	<td><label for="nombreplan" id="nombreplan-idioma">Nombre del Plan</label></td>
								    	<td><input id="nombreplan" maxlength="30" style="width:210px;" onkeypress="return validarNumerosLetrasPorcentageEspacio(event);"></input></td>
									    <td><label for="empresa-sucursal" id="empresasucursal-idioma">Sucursal</label></td>
									    <td><select class="input-small" name="empresa-sucursal" id="empresa-sucursal" style="width:150px;"><option value="-1">---Seleccione---</option></select></td>
								    </tr>
								</table>
							</fieldset>
							
					</div>
				</div>
				<div  id="tab-content">
		 		    <div id="contenedor" style="width:1100px;">
		 		   		<a id="buscarplan"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Buscar"  style="cursor: hand;"/></a>
		 		   		<a id="nuevoplan"  class="btn btn-info" href="#modalEditar" data-toggle="modal"><img src="<?= $this->baseUrl() . "/css/images/nuevo.png"; ?>" id="nuevo-img" title="Nuevo"  style="cursor: hand;"/></a>
		 		   		<a id="imprimirplan"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/guardar.png"; ?>" id="guardar-img" title="Guardar/Abrir"  style="cursor: hand;"/></a>
		 		   </div> 
				</div>
				<div id="contenedor" style="width:1100px;">
				 		<fieldset>
								  <table border="0">
								  	<tr>
								  		<td>
									  		<div class="tab-content" id="tab-content">
							                    <!-- DATOS DE IMPUESTOS --->
							                    		<div id="grillaPaginadorPlanes">
							                    			<table id="grillaPlanes"></table>
								                    		<div id="paginadorPlanes"></div>
								                    	</div>
								                    	
								            </div>
								    	</td>
							       	</tr>
								</table>
							</fieldset>
				</div>
				
 	</div>	
	</div>
	</div>
	</div>
	
	</CENTER>
</body>
</html> 