<?php 
$titulo = "Listado de Camiones";
    $labelDescripcion = "Busqueda por Proveedor/Marca/Modelo/Anho/Peso Neto/Chapa";
    $labelsGrillas = array('Proveedor','Marca','Modelo','Anho','Peso Neto','Chapa');
   
    $idCamposGrilla = array("id-registro","selectProveedor","marca_camion","modelo_camion","anho_camion","peso_neto_camion","chapa_camion");
?>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10" id="span10">
            <br>
                <div id="cabeceraFormulario" class="btn btn-info" >
                    <h1 id="cabecera-titulo" align="center" ><?php echo $titulo ?></h1>

                    <div class="alert alert-block hide" id="warning-block-registro-listado">
                        <div id="warning-message-registro-listado"></div>
                    </div>

                    <div class="alert alert-success hide" id="success-block-registro-listado">
                        <div id="success-message-registro-listado"></div>
                    </div>

                    <div class="alert alert-error hide" id="error-block-registro-listado">
                    </div>

                    <div class="alert alert-info hide" id="info-block-listado">
                        <div id="info-message"></div>
                    </div>



                </div>
                <div  id="clientes-div">
                    <div id="contenedor" >
                        <fieldset>
                            <table border="0">
                                <tr>
                                    <td><label for="descripcionBusqueda" id="descripcionBusqueda-idioma"><?php echo $labelDescripcion ?></label></td>
                                    <td><input id="descripcionBusqueda" maxlength="50"  onkeypress='return validarNumerosLetrasPorcentageEspacio(event);'></input></td>
                                </tr>
                            </table>
                        </fieldset>

                </div>
            </div>
            <div  id="tab-content">
                <div id="contenedor" >
                    <a id="buscarregistro"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Buscar"  style="cursor: hand;"/></a>
                    <a id="nuevoregistro"  class="btn btn-info"  data-toggle="modal"><img src="<?= $this->baseUrl() . "/css/images/nuevo.png"; ?>" id="nuevo-img" title="Nuevo"  style="cursor: hand;"/></a>
                </div>
            </div>
            <div id="contenedor" >
                <fieldset>
                    <table border="0">
                        <tr>
                            <td>
                                <div class="tab-content" id="tab-content">
                                    <div id="grillaPaginadorRegistro">
                                        <table id="grillaRegistro"></table>
                                        <div id="paginadorRegistro"></div>
                                    </div>

                                </div>
                            </td>
                        </tr>
                    </table>
                </fieldset>
            </div>

    </div>
</div>
</div>