<header class="text-center">
	<h3>Camión </h3>	
</header>
<div class="col-lg-12">
	<div class="col-lg-6">
		<div class="form-group">
            <label for="query" class="control-label">Search: </label>
            <input class="form-control" name="query" id="query-1" placeholder="Start typing something to search..." type="text">              
        </div>
	</div>
	<div class="col-lg-6">
		<div class="form-group">
            <label for="query" class="control-label">Search3: </label>
            <input class="form-control" name="query" id="query-2" placeholder="Start typing something to search..." type="text">              
        </div>
	</div>
</div>
<div class="col-lg-12">
	<div class="col-lg-6">
		<div class="control-group">
			<div class="form-group">
		        <label for="single" class="control-label">Select2 single select spans</label>
		       
		          <select id="span_1" class="select2 form-control">
		            <option></option>
		            <option value="A">HOLA OPCION 1 </option>
		            <option value="B">HOLA OPCION 2 </option>
		            <option value="C">HOLA OPCION 4 </option>
		          </select>
		    </div>      
	    </div>      
    </div>      
</div>
<div class="col-lg-12">
	<div class="col-lg-6">
		<div class="control-group">
			<div class="form-group">
				<label for="single" class="control-label">Date</label>
                <input id="datetimepicker" type="text" class="form-control">
            </div>     
    	</div> 
	</div> 
    <div class="col-lg-6">
		<div class="control-group">
			<div class="form-group">
				<label for="single" class="control-label">Date</label>
                <input id="datetimepicker" type="text" class="form-control">
            </div>     
        </div>     
    </div>      
</div>
<style type="text/css">
	.twitter-typeahead, .tt-hint, .tt-input, .tt-menu { width: 100%; }
</style>

<script type="text/javascript" 
	src="<?php echo $this->baseUrl(). "/js/bootstrap3-typeahead.js"?>">
</script>
<script type="text/javascript">


$('#query-1').typeahead({        
        local: ['alpha','allpha2','alpha3','bravo','charlie','delta','epsilon','gamma','zulu']
});
$('#query-2').typeahead({        
        local: ['alpha','allpha2','alpha3','bravo','charlie','delta','epsilon','gamma','zulu']
});                                                                                                      
$('.tt-query').css('background-color','#fff');     

 $('.select2').select2({ placeholder : '' });

  $('.select2-remote').select2({ data: [{id:'A', text:'A'}]});

  $('button[data-select2-open]').click(function(){
    $('#' + $(this).data('select2-open')).select2('open');
  });

  jQuery('#datetimepicker').datetimepicker();
</script>