<!DOCTYPE html>
<html lang="en" class="no-js">
    <head>
        <meta charset="UTF-8" />
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
        <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1-rc.1/css/select2.min.css" rel="stylesheet" />
        <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1-rc.1/js/select2.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(). "/js/jquery.datetimepicker.js"?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl(). "/js/jquery.datetimepicker.full.min.js"?>"></script>
        <link rel="stylesheet" href="<?php echo $this->baseUrl(). "/css/jquery.datetimepicker.css"?>" />
    </head>
    <body>
        <div class="">
            <nav class="navbar navbar-default" role="navigation">
                <!-- El logotipo y el icono que despliega el menú se agrupan
                    para mostrarlos mejor en los dispositivos móviles -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Desplegar navegación</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Sistema Logo</a>
                </div>
                <!-- Agrupar los enlaces de navegación, los formularios y cualquier
                    otro elemento que se pueda ocultar al minimizar la barra -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                            <a href="<?php echo $this->baseUrl(). "/index.php/administrativo/chofer"?>">Chofer</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->baseUrl(). "/index.php/administrativo/camion"?>">Camión</a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Menú #1 <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#">Acción #1</a>
                                </li>
                                <li>
                                    <a href="#">Acción #2</a>
                                </li>
                                <li>
                                    <a href="#">Acción #3</a>
                                </li>
                                <li class="divider">
                                </li>
                                <li>
                                    <a href="#">Acción #4</a>
                                </li>
                                <li class="divider">
                                </li>
                                <li>
                                    <a href="#">Acción #5</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="#">Enlace #3</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Menú #2 <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Acción #1</a></li>
                                <li><a href="#">Acción #2</a></li>
                                <li><a href="#">Acción #3</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Acción #4</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="">
                
                    <?php
                        echo $this->layout()->content;
                        ?>
                
            </div>
            <!-- /content-wrap -->
        </div>
        <!-- /container -->
        
    </body>
</html>